"""Canonical Regional generation contracts."""

from modules_nocturne.regional.errors import IssueSeverity, PlanError, ValidationIssue, ValidationReport
from modules_nocturne.regional.capabilities import (
    AdapterRegistry,
    CapabilityReport,
    CapabilityService,
    EngineCapabilities,
    EngineRegistry,
    RegionalEngine,
    RegionalModelAdapter,
    capability_service,
)
from modules_nocturne.regional.model import (
    CURRENT_SCHEMA,
    Canvas,
    Composition,
    EngineSelection,
    GlobalPrompt,
    GuidanceSchedule,
    OverlapPolicy,
    PassPolicy,
    Point,
    PolygonGeometry,
    RasterMaskGeometry,
    RectGeometry,
    Region,
    RegionalGenerationPlan,
    SeedMode,
    SeedPolicy,
    UncoveredPolicy,
    new_region,
)
from modules_nocturne.regional.project import (
    MetadataBundle,
    RestoredRegionalMetadata,
    build_metadata,
    load_project,
    restore_metadata,
    save_project,
    save_sidecar,
    sidecar_path_for,
)
from modules_nocturne.regional.prompts import (
    CompiledPromptPlan,
    CompiledPromptText,
    CompiledRegionPrompts,
    EncodingRequest,
    PromptExpansionContext,
    PromptExpansionService,
    PromptOwner,
    compile_prompt_plan,
)
from modules_nocturne.regional.seeds import ResolvedSeedPlan, derive_region_seed, resolve_seed_plan
from modules_nocturne.regional.serialization import canonical_json, load_plan, plan_hash, save_plan
from modules_nocturne.regional.validation import ValidationCapabilities, validate_plan

__all__ = [
    "CURRENT_SCHEMA",
    "AdapterRegistry",
    "Canvas",
    "CapabilityReport",
    "CapabilityService",
    "Composition",
    "CompiledPromptPlan",
    "CompiledPromptText",
    "CompiledRegionPrompts",
    "EngineSelection",
    "EngineCapabilities",
    "EngineRegistry",
    "EncodingRequest",
    "GlobalPrompt",
    "GuidanceSchedule",
    "IssueSeverity",
    "MetadataBundle",
    "OverlapPolicy",
    "PassPolicy",
    "PlanError",
    "Point",
    "PolygonGeometry",
    "PromptExpansionContext",
    "PromptExpansionService",
    "PromptOwner",
    "RasterMaskGeometry",
    "RectGeometry",
    "Region",
    "RegionalGenerationPlan",
    "RegionalEngine",
    "RegionalModelAdapter",
    "ResolvedSeedPlan",
    "RestoredRegionalMetadata",
    "SeedMode",
    "SeedPolicy",
    "UncoveredPolicy",
    "ValidationCapabilities",
    "ValidationIssue",
    "ValidationReport",
    "canonical_json",
    "capability_service",
    "build_metadata",
    "compile_prompt_plan",
    "derive_region_seed",
    "load_plan",
    "load_project",
    "new_region",
    "plan_hash",
    "resolve_seed_plan",
    "restore_metadata",
    "save_project",
    "save_sidecar",
    "save_plan",
    "sidecar_path_for",
    "validate_plan",
]
