"""Canonical Regional generation contracts."""

from modules_nocturne.regional.errors import IssueSeverity, PlanError, ValidationIssue, ValidationReport
from modules_nocturne.regional.model import (
    CURRENT_SCHEMA,
    Canvas,
    Composition,
    EngineSelection,
    GlobalPrompt,
    GuidanceSchedule,
    OverlapPolicy,
    PassPolicy,
    Point,
    PolygonGeometry,
    RasterMaskGeometry,
    RectGeometry,
    Region,
    RegionalGenerationPlan,
    SeedMode,
    SeedPolicy,
    UncoveredPolicy,
    new_region,
)
from modules_nocturne.regional.seeds import ResolvedSeedPlan, derive_region_seed, resolve_seed_plan
from modules_nocturne.regional.serialization import canonical_json, load_plan, plan_hash, save_plan
from modules_nocturne.regional.validation import ValidationCapabilities, validate_plan

__all__ = [
    "CURRENT_SCHEMA",
    "Canvas",
    "Composition",
    "EngineSelection",
    "GlobalPrompt",
    "GuidanceSchedule",
    "IssueSeverity",
    "OverlapPolicy",
    "PassPolicy",
    "PlanError",
    "Point",
    "PolygonGeometry",
    "RasterMaskGeometry",
    "RectGeometry",
    "Region",
    "RegionalGenerationPlan",
    "ResolvedSeedPlan",
    "SeedMode",
    "SeedPolicy",
    "UncoveredPolicy",
    "ValidationCapabilities",
    "ValidationIssue",
    "ValidationReport",
    "canonical_json",
    "derive_region_seed",
    "load_plan",
    "new_region",
    "plan_hash",
    "resolve_seed_plan",
    "save_plan",
    "validate_plan",
]
